apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: 'cluster1'
  namespace: 'cluster1'
  labels:
    cloud: 'AWS'
    region: 'eu-west-2'
    vendor: OpenShift
spec:
  baseDomain: sandbox1900.opentlc.com
  clusterName: 'cluster1'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: cluster1-aws-creds
      region: eu-west-2
  provisioning:
    installConfigSecretRef:
      name: cluster1-install-config
    sshPrivateKeySecretRef:
      name: cluster1-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.19.18-multi
      name: img4.19.18-multi-appsub
  pullSecretRef:
    name: cluster1-pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: eu-west-2
    name: 'cluster1'
    vendor: OpenShift
    environment: 'prod'
  name: 'cluster1'
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: cluster1-worker
  namespace: 'cluster1'
spec:
  clusterDeploymentRef:
    name: 'cluster1'
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-pull-secret
  namespace: 'cluster1'
stringData:
  .dockerconfigjson: eyJhdXRocyI6eyJjbG91ZC5vcGVuc2hpZnQuY29tIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzI5amJWOWhZMk5sYzNOZk5ESXdPV1ptWm1WbU5HRTBORGM0TUdFeFl6VXlOekkzT1RVek9HRmxZMk02VWxOV09WbE9VVU5MV0VaR1dVSktNMEpETlRnMFQweFpNa2hGU2tGSldqbGFTbGN5T1RFNFQwTldSalkzUkZrMk4xZFJXRFpCU0RaUlZqYzFTRVZUTVE9PSIsImVtYWlsIjoiZHR1cmdlbWFAcmVkaGF0LmNvbSJ9LCJxdWF5LmlvIjp7ImF1dGgiOiJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzI5amJWOWhZMk5sYzNOZk5ESXdPV1ptWm1WbU5HRTBORGM0TUdFeFl6VXlOekkzT1RVek9HRmxZMk02VWxOV09WbE9VVU5MV0VaR1dVSktNMEpETlRnMFQweFpNa2hGU2tGSldqbGFTbGN5T1RFNFQwTldSalkzUkZrMk4xZFJXRFpCU0RaUlZqYzFTRVZUTVE9PSIsImVtYWlsIjoiZHR1cmdlbWFAcmVkaGF0LmNvbSJ9LCJyZWdpc3RyeS5jb25uZWN0LnJlZGhhdC5jb20iOnsiYXV0aCI6ImZIVm9ZeTF3YjI5c0xUQmtZVGhrTVRCa0xUYzBZbU10TkdFek9DMDRZV1EzTFdSa1lqTTFaakZrTVRRNU1UcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU1RKTk1sVjNUa2RSTkU5RVdUTmFSMUV3VFZSVmVsbHFSbXhhUkVKcFRucHJNbHBFWkdsUFIxVTFUVk5LT1M1SWMyazRha0Y1VTBGUE1VWkhkbVV4V2xSYVpYVlJlRTVMU1habFMzUlJhRkZwYzB0RU1YUnZka2N5UzI5WU5rOW9SRE5mY0MxTU1HNUpSMkU1TlRkdlZETjBjREZFWWw5amFrSmpkMFY0VTI1UGFVdDBUbEJ6WlVOR1JqZFlhSHAyY2xCSVJXczRURE0yY1dKWVUyUjBSV2MwVm14M1JISmZjV2RPYVRock5uRmphVlE0YUc5a2MyZDVSekpaTFROQlIyNVhkVXRWZVZsb2QyMUVVV1V3TVhKYU5HeHBTVGxIZHpsTVpUZEJlbGs1ZDBSWWEwTmtkWEY1YkRkc2VVTXhheTB6V0hCSFZVNTRkMk5FYzJWSFkxRlZWbmxJWkdsV1IyWnRXVTVUVVhoMlVEZFBVMEZHVGpZNFIwSTVkMFEzTUc5QmRYVnNVbVZPZEZFMmVHeFVSVGh1VVRkcGEyMU1TMnBxYmpSRWJtRkdaelV0VVdsaVdHOUpRbE5aZWxSSFZtcEVOVkIwVkdST2JqaE5hVWR5TkZkSGNHZDNhbU5tYzNSbmVIQmFaSEpxVWpVNVVYbE1kR1JrUW5acE5XZEVVVVYzUW1FMWVGRnNURXRFTFdkVWVUbEpaVlZzZFRSTFlWUXhiRXhDU2pCMlRYQXhNRXBqY1dKb056ZE5PVGxRV0ZrMFp6aFdWemRmVGxOVmRVSk9SR3cwV1ROdVdWZzFNM1pzVTFoVU4xaHJZall0UlZBNVFXZFZaRkpqYW1SdmNtOXhORjlUTmpSWlZrTllPR2MwV0hwNU5rNVdlamxoUzFKMmNGVlhXVlkwVm1wVFVURnRkMDlNWVVkRFExOW9TVEJ5UlU5SlVYZFVObUpEVFRkamEzTkVkbDlVTkMxdlJWWnhVMjV5UmxNeGVtWldiemRXYm10SFFVVm5WbUZtYTNrMk1uQXhablpVUlcxVlFtMHdTVE5tZVZWTVQzbHRXblZRY201YVptMDFZMVJhY1Vac1FrVndTREZsZWtoVE1sYzFPWGt0Uldjd1NIZDFZMm90VVdsS1FqQm5NSFIyVUZoUGRFZ3RVMnhmYlZOSlEwTmtaSE5WTFhBd1FsaFJYMU5NU25KclRFbHFiWFJCYzFJNFYxRXhhMmd4TFVGTExXSXpka0pOYTBoVU1qUlBPRTAxVlhOSlNucEZUakpqV1dKbVduVTFVVE5QVVE9PSIsImVtYWlsIjoiZHR1cmdlbWFAcmVkaGF0LmNvbSJ9LCJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6ImZIVm9ZeTF3YjI5c0xUQmtZVGhrTVRCa0xUYzBZbU10TkdFek9DMDRZV1EzTFdSa1lqTTFaakZrTVRRNU1UcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU1RKTk1sVjNUa2RSTkU5RVdUTmFSMUV3VFZSVmVsbHFSbXhhUkVKcFRucHJNbHBFWkdsUFIxVTFUVk5LT1M1SWMyazRha0Y1VTBGUE1VWkhkbVV4V2xSYVpYVlJlRTVMU1habFMzUlJhRkZwYzB0RU1YUnZka2N5UzI5WU5rOW9SRE5mY0MxTU1HNUpSMkU1TlRkdlZETjBjREZFWWw5amFrSmpkMFY0VTI1UGFVdDBUbEJ6WlVOR1JqZFlhSHAyY2xCSVJXczRURE0yY1dKWVUyUjBSV2MwVm14M1JISmZjV2RPYVRock5uRmphVlE0YUc5a2MyZDVSekpaTFROQlIyNVhkVXRWZVZsb2QyMUVVV1V3TVhKYU5HeHBTVGxIZHpsTVpUZEJlbGs1ZDBSWWEwTmtkWEY1YkRkc2VVTXhheTB6V0hCSFZVNTRkMk5FYzJWSFkxRlZWbmxJWkdsV1IyWnRXVTVUVVhoMlVEZFBVMEZHVGpZNFIwSTVkMFEzTUc5QmRYVnNVbVZPZEZFMmVHeFVSVGh1VVRkcGEyMU1TMnBxYmpSRWJtRkdaelV0VVdsaVdHOUpRbE5aZWxSSFZtcEVOVkIwVkdST2JqaE5hVWR5TkZkSGNHZDNhbU5tYzNSbmVIQmFaSEpxVWpVNVVYbE1kR1JrUW5acE5XZEVVVVYzUW1FMWVGRnNURXRFTFdkVWVUbEpaVlZzZFRSTFlWUXhiRXhDU2pCMlRYQXhNRXBqY1dKb056ZE5PVGxRV0ZrMFp6aFdWemRmVGxOVmRVSk9SR3cwV1ROdVdWZzFNM1pzVTFoVU4xaHJZall0UlZBNVFXZFZaRkpqYW1SdmNtOXhORjlUTmpSWlZrTllPR2MwV0hwNU5rNVdlamxoUzFKMmNGVlhXVlkwVm1wVFVURnRkMDlNWVVkRFExOW9TVEJ5UlU5SlVYZFVObUpEVFRkamEzTkVkbDlVTkMxdlJWWnhVMjV5UmxNeGVtWldiemRXYm10SFFVVm5WbUZtYTNrMk1uQXhablpVUlcxVlFtMHdTVE5tZVZWTVQzbHRXblZRY201YVptMDFZMVJhY1Vac1FrVndTREZsZWtoVE1sYzFPWGt0Uldjd1NIZDFZMm90VVdsS1FqQm5NSFIyVUZoUGRFZ3RVMnhmYlZOSlEwTmtaSE5WTFhBd1FsaFJYMU5NU25KclRFbHFiWFJCYzFJNFYxRXhhMmd4TFVGTExXSXpka0pOYTBoVU1qUlBPRTAxVlhOSlNucEZUakpqV1dKbVduVTFVVE5QVVE9PSIsImVtYWlsIjoiZHR1cmdlbWFAcmVkaGF0LmNvbSJ9fX0=
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-install-config
  namespace: 'cluster1'
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogJ2NsdXN0ZXIxJwpiYXNlRG9tYWluOiBzYW5kYm94MTkwMC5vcGVudGxjLmNvbQpjb250cm9sUGxhbmU6CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDQwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCmNvbXB1dGU6Ci0gaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiAnd29ya2VyJwogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogMjAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS54bGFyZ2UKbmV0d29ya2luZzoKICBuZXR3b3JrVHlwZTogT1ZOS3ViZXJuZXRlcwogIGNsdXN0ZXJOZXR3b3JrOgogIC0gY2lkcjogMTAuMTI4LjAuMC8xNAogICAgaG9zdFByZWZpeDogMjMKICBtYWNoaW5lTmV0d29yazoKICAtIGNpZHI6IDEwLjAuMC4wLzE2CiAgc2VydmljZU5ldHdvcms6CiAgLSAxNzIuMzAuMC4wLzE2CnBsYXRmb3JtOgogIGF3czoKICAgIHJlZ2lvbjogZXUtd2VzdC0yCnB1bGxTZWNyZXQ6ICIiICMgc2tpcCwgaGl2ZSB3aWxsIGluamVjdCBiYXNlZCBvbiBpdCdzIHNlY3JldHMKc3NoS2V5OiB8LQogICAgc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFBZ1FEWWFJOG9YalVCS1dGdERTV2JzMDNSVlhMS0xWdTh2cHZ1YStBV1ovVlc5NlZBdFhOMy84TGlIdzZnR1REU1FiY2s5ekNPUFRETmxGOHYxOEJhRkVHYnhpZDFMcHh2Y1VIVHovdEwrOTZqQVdabnpUUjM3bkZnQXRhbzVkdWtKRkpHOGtFMTBRRTh3VkI4TUZ0clk2bUdQMlpFMkc1dE1GRldLWERKeUdhNHB3PT0gbm9uYW1lCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-ssh-private-key
  namespace: 'cluster1'
stringData:
  ssh-privatekey: # injected on create
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cluster1-aws-creds
  namespace: 'cluster1'
stringData:
  aws_access_key_id: AKIA4CS3Z3GD24ELBAU5
  aws_secret_access_key: # injected on create
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'cluster1'
  namespace: 'cluster1'
spec:
  clusterName: 'cluster1'
  clusterNamespace: 'cluster1'
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
