apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: 'doron'
  namespace: 'doron'
  labels:
    cloud: 'AWS'
    region: 'eu-west-2'
    vendor: OpenShift
spec:
  baseDomain: sandbox1900.opentlc.com
  clusterName: 'doron'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: doron-aws-creds
      region: eu-west-2
  provisioning:
    installConfigSecretRef:
      name: doron-install-config
    sshPrivateKeySecretRef:
      name: doron-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.19.18-multi
      name: img4.19.18-multi-appsub
  pullSecretRef:
    name: doron-pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: eu-west-2
    name: 'doron'
    vendor: OpenShift
    environment: 'prod'
  name: 'doron'
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: doron-worker
  namespace: 'doron'
spec:
  clusterDeploymentRef:
    name: 'doron'
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: doron-pull-secret
  namespace: 'doron'
stringData:
  .dockerconfigjson: # injected on create
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: doron-install-config
  namespace: 'doron'
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogJ2Rvcm9uJwpiYXNlRG9tYWluOiBzYW5kYm94MTkwMC5vcGVudGxjLmNvbQpjb250cm9sUGxhbmU6CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDQwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCmNvbXB1dGU6Ci0gaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiAnd29ya2VyJwogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogMjAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS54bGFyZ2UKbmV0d29ya2luZzoKICBuZXR3b3JrVHlwZTogT1ZOS3ViZXJuZXRlcwogIGNsdXN0ZXJOZXR3b3JrOgogIC0gY2lkcjogMTAuMTI4LjAuMC8xNAogICAgaG9zdFByZWZpeDogMjMKICBtYWNoaW5lTmV0d29yazoKICAtIGNpZHI6IDEwLjAuMC4wLzE2CiAgc2VydmljZU5ldHdvcms6CiAgLSAxNzIuMzAuMC4wLzE2CnBsYXRmb3JtOgogIGF3czoKICAgIHJlZ2lvbjogZXUtd2VzdC0yCnB1bGxTZWNyZXQ6ICIiICMgc2tpcCwgaGl2ZSB3aWxsIGluamVjdCBiYXNlZCBvbiBpdCdzIHNlY3JldHMKc3NoS2V5OiB8LQogICAgc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFBZ1FEWWFJOG9YalVCS1dGdERTV2JzMDNSVlhMS0xWdTh2cHZ1YStBV1ovVlc5NlZBdFhOMy84TGlIdzZnR1REU1FiY2s5ekNPUFRETmxGOHYxOEJhRkVHYnhpZDFMcHh2Y1VIVHovdEwrOTZqQVdabnpUUjM3bkZnQXRhbzVkdWtKRkpHOGtFMTBRRTh3VkI4TUZ0clk2bUdQMlpFMkc1dE1GRldLWERKeUdhNHB3PT0gbm9uYW1lCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: doron-ssh-private-key
  namespace: 'doron'
stringData:
  ssh-privatekey: # injected on create
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: doron-aws-creds
  namespace: 'doron'
stringData:
  aws_access_key_id: AKIA4CS3Z3GD24ELBAU5
  aws_secret_access_key: # injected on create
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'doron'
  namespace: 'doron'
spec:
  clusterName: 'doron'
  clusterNamespace: 'doron'
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
