apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: 'cluster1'
  namespace: 'cluster1'
  labels:
    cloud: 'AWS'
    region: 'eu-west-2'
    vendor: OpenShift
spec:
  baseDomain:
  clusterName: 'cluster1'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: cluster1-aws-creds
      region: eu-west-2
  provisioning:
    installConfigSecretRef:
      name: cluster1-install-config
    sshPrivateKeySecretRef:
      name: cluster1-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-dev/ocp-release:4.19.18-multi
      name: img4.19.18-multi-appsub
  pullSecretRef:
    name: cluster1-pull-secret
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: eu-west-2
    name: 'cluster1'
    vendor: OpenShift
    environment: 'prod'
  name: 'cluster1'
spec:
  hubAcceptsClient: true
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: cluster1-worker
  namespace: 'cluster1'
spec:
  clusterDeploymentRef:
    name: 'cluster1'
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster1-install-config
  namespace: 'cluster1'
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogJ2NsdXN0ZXIxJwpiYXNlRG9tYWluOgpjb250cm9sUGxhbmU6CiAgaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiBtYXN0ZXIKICByZXBsaWNhczogMwogIHBsYXRmb3JtOgogICAgYXdzOgogICAgICByb290Vm9sdW1lOgogICAgICAgIGlvcHM6IDQwMDAKICAgICAgICBzaXplOiAxMDAKICAgICAgICB0eXBlOiBpbzEKICAgICAgdHlwZTogbTUueGxhcmdlCmNvbXB1dGU6Ci0gaHlwZXJ0aHJlYWRpbmc6IEVuYWJsZWQKICBuYW1lOiAnd29ya2VyJwogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogMjAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS54bGFyZ2UKbmV0d29ya2luZzoKICBuZXR3b3JrVHlwZTogT1ZOS3ViZXJuZXRlcwogIGNsdXN0ZXJOZXR3b3JrOgogIC0gY2lkcjogMTAuMTI4LjAuMC8xNAogICAgaG9zdFByZWZpeDogMjMKICBtYWNoaW5lTmV0d29yazoKICAtIGNpZHI6IDEwLjAuMC4wLzE2CiAgc2VydmljZU5ldHdvcms6CiAgLSAxNzIuMzAuMC4wLzE2CnBsYXRmb3JtOgogIGF3czoKICAgIHJlZ2lvbjogZXUtd2VzdC0yCnB1bGxTZWNyZXQ6ICIiICMgc2tpcCwgaGl2ZSB3aWxsIGluamVjdCBiYXNlZCBvbiBpdCdzIHNlY3JldHMK
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cluster1-aws-creds
  namespace: 'cluster1'
stringData:
  aws_access_key_id: 
  aws_secret_access_key: # injected on create
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'cluster1'
  namespace: 'cluster1'
spec:
  clusterName: 'cluster1'
  clusterNamespace: 'cluster1'
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
